version: "3"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
      -
  nginx:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - board-games-web-service
      - board-games-backend-service


  board-games-backend-service:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./BoardGamesApi"
    volumes:
      - ./BoardGameApi:/home/node/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=BoardGamesApi
      - PORT=4000
      - API_HOST=localhost

  board-games-web-service:
    restart: "always"
    build:
      dockerfile: Dockerfile
      context: "./BoardGamesApp"
    volumes:
      - ./BoardGamesApp:/opt/app
    depends_on:
      - board-games-backend-service
